FROM elixir:1.14-alpine

WORKDIR /app

# Set environment to prod
ENV MIX_ENV=prod

RUN apk add --no-cache build-base npm git python3

RUN mix local.hex --force && \
    mix local.rebar --force

COPY mix.exs mix.lock ./
COPY config config
RUN mix deps.get --only prod

# Copy assets first and install npm dependencies
COPY assets assets
RUN cd assets && npm install

# Copy remaining files
COPY priv priv
COPY lib lib

# Deploy assets with MIX_ENV=prod
RUN mix assets.deploy

EXPOSE 4000
CMD ["mix", "phx.server"]